name: CI/CD Pipeline

on: 
  push:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v3

      # Sets up Docker Buildx to enable advanced Docker build features
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

      # Uses Docker login action to authenticate with Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        # Retrieves the Docker Hub username from GitHub Secrets
        username: ${{ secrets.DOCKER_USERNAME }}
        # Retrieves the Docker Hub password from GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}

      # Uses Docker's build-push action to build and push Docker images
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        # Specifies the current directory
        context: .
        # Instructs Docker to push the image to Docker Hub after building
        push: true
        # Specifies the image name and tag to be pushed
        tags: leshaan99/counter-app:latest

      # Logs out from Docker Hub to remove the authentication credentials from the environment
    - name: Log out from Docker Hub
      run: docker logout

  deploy-to-ec2:
    needs: build-and-push
    runs-on: aws-ec2
