name: CI/CD Pipeline

on: 
  push:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v3

      # Sets up Docker Buildx to enable advanced Docker build features
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

      # Uses Docker login action to authenticate with Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        # Retrieves the Docker Hub username from GitHub Secrets
        username: ${{ secrets.DOCKER_USERNAME }}
        # Retrieves the Docker Hub password from GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}

      # Uses Docker's build-push action to build and push Docker images
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        # Specifies the current directory
        context: .
        # Instructs Docker to push the image to Docker Hub after building
        push: true
        # Specifies the image name and tag to be pushed
        tags: leshaan99/counter-app:latest

      # Logs out from Docker Hub to remove the authentication credentials from the environment
    - name: Log out from Docker Hub
      run: docker logout

  deploy-to-ec2:
    needs: build-and-push
    # The job is executed on an AWS EC2 instance
    runs-on: aws-ec2
    steps:
      - name: Pull image from the docker hub
        # Pulls the latest version of the Docker image
        run: docker full leshaan99/counter-app:latest
      - name: Delete old container
        # Removes any existing container named 'reactContainer'
        run: docker rm -f reactContainer
      - name: Run the docker container
        # Runs a new Docker container from the pulled image in detached mode
        # mapping port 3000 of the container to port 3000 of the EC2 instance
        # Names the container 'reactContainer'
        run: docker run -d -p 3000:3000 --name reactContainer leshaan99/counter-app
